genysis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('quiz/', include('quiz.urls')),
]

quiz/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'quiz'
urlpatterns = [
    path('', views.IndexView.as_view(), name = 'index'),
    path('category/<int:category_id>', views.category, name='category'),
    path('dev/', TemplateView.as_view(template_name = 'quiz/development.html'), name = 'development'),
]

quiz/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    text = models.CharField(max_length = 255)
    date_added = models.DateTimeField(auto_now_add=True)
    published = models.BooleanField(default = 1)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)

    def __str__(self):
        return self.text

class Answer(models.Model):
    text = models.CharField(max_length = 255)
    date_added = models.DateTimeField(auto_now_add=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    correct = models.BooleanField(default=False)

    def is_correct(self):
        return self.correct
    
    def __str__(self):
        return self.text

class Category(models.Model):
    name = models.CharField(max_length = 255)
    date_added = models.DateTimeField(auto_now_add=True)
    published = models.BooleanField(default = 1)

    def __str__(self):
        return self.name

quiz/views.py
from django.shortcuts import render, get_object_or_404
from quiz.models import Question, Answer, Category
from django.views.generic import ListView, DetailView

# Create your views here.

class IndexView(ListView):
    model = Category
    template_name = 'quiz/index.html'
    context_object_name = 'categories'

    def get_queryset(self):
        return Category.objects.order_by('-date_added')[:10]

def category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    print(category)
    questions = Question.objects.filter(category__id=category.id)
    context = {
        'category':category,
        'questions':questions
    }
    return render(request, 'quiz/category-detail.html', context)

quiz/templates/quiz/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>{% block title %} {% endblock %}</title>
        <link rel = "stylesheet" href = "{% static 'quiz/bootstrap_5.0/css/bootstrap.min.css' %}">
    </head>
    <body>
        <div class = "container">
            <section class = "mt-2">
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <div class="container-fluid">
                      <a class="navbar-brand" href="#">Genysis</a>
                      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                          <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Quiz</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'quiz:development' %}">Development Status</a>
                          </li>
                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Account
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                              <li><a class="dropdown-item" href="#">Login</a></li>
                              <li><a class="dropdown-item" href="#">Help Center</a></li>
                              <!--
                              <li><hr class="dropdown-divider"></li>
                              <li><a class="dropdown-item" href="#">Something else here</a></li>
                              -->
                            </ul>
                          </li>
                          <!--
                          <li class="nav-item">
                            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                          </li>
                        -->
                        </ul>
                        <form class="d-flex">
                          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                          <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                      </div>
                    </div>
                </nav>
            </section>

            <section class = "container bg-warning p-1 pt-3" style = "display:none">
                <p>Notification Always Goes Here</p>
            </section>

            <section class = "mt-5">
              {% block content %}
              {% endblock %}
            </section>
            
        </div>
        <script src = "{% static 'quiz/jquery/jquery-3.6.1.min.js' %}"></script>
        <script src = "{% static 'quiz/bootstrap_5.0/js/bootstrap.min.js' %}"></script>

        {% block javascript %}
        {% endblock %}
    </body>
</html>

quiz/templates/quiz/category-detail.html
{% extends 'quiz/base.html' %}

{% block content %}
<div align = "center">
    <h4>{{ category.name }}</h4>
</div>

<div class = "row">
    <div class = "offset-md-2 col-md-8">
        {% for question in questions %}
        <div class = "question_list mt-4" id = "qrow-{{ question.id }}">
            <p class = "bg-warning p-2">Question</p>
            <p>{{ question.text }}</p>
            <hr>
            <small class = "text-danger" style="font-style:italic">Options</small>
            {% for answer in question.answer_set.all %}
            <div class = "mt-4">
                <div class = "form-group">
                    <input type = "radio" class = "">
                    <label>{{ answer.text }}</label>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endfor %}
        <div align = "right">
            <button class = "btn btn-primary" id = "nextBtn">Next</button>    
        </div>
    </div>
</div>

{% endblock %}

{% block javascript %}
<script>
    function clearQuestions(object){
        object.forEach(element => element.style.display = 'none');
    }

    question_list = document.querySelectorAll('.question_list')
    clearQuestions(question_list)
    questions = question_list.length
    question_list[0].style.display = 'block'
    question_index = 0

    function nextBtn(){
        console.log('reached here')
        clearQuestions(question_list)
        question = question_index+1
        question_list[question].style.display = 'block'
        console.log(question_list[question])
    }


    $("#nextBtn").click(function(){
        nextBtn()
    })
</script>
{% endblock %}

quiz/templates/quiz/development.html
{% extends 'quiz/base.html' %}

{% block content %}
<section class = "mt-5">
    <h4>Development Status</h4>
    <hr>
    <div>
        <small class = "bg-primary p-2 text-light">Friday September 2, 2022</small>
        <p>
            <ul>
                <li>Added custom javascript to facilitate question switching</li>
                <li>Added the 'Development Status' Page to the app</li>
                <li>Configured the Next Button to work and also removed the previous button</li>
            </ul>
        </p>
    </div>

    <div>
        <small class = "bg-primary p-2 text-light">Saturday September 3, 2022</small>
        <p>
            <ul>
                <li></li>
            </ul>
        </p>
    </div>
</section>
{% endblock %}

quiz/templates/quiz/index.html
{% extends 'quiz/base.html' %}

{% block content %}
<div>
    <div class = "row">
        <div class = "offset-md-4 col-md-4" align = "center">
            <h3>Choose A Category</h3>
            <div class = "d-grid gap-2">
                {% for category in categories %}
                <a href="{% url 'quiz:category' category.id %}" class = "btn btn-primary">{{ category.name }}<a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}